import type { Course } from '../types';

/**
 * A static dataset of all available courses.
 * In a real-world application, this would likely be fetched from an API.
 */
const courses: Course[] = [
  {
    id: 'mkt101',
    title: 'Digital Marketing Fundamentals',
    title_vi: 'Nền tảng Marketing Kỹ thuật số',
    provider: 'In-House Experts',
    description: 'A comprehensive intro to digital marketing, from SEO to social media.',
    description_vi: 'Giới thiệu toàn diện về marketing kỹ thuật số, từ SEO đến mạng xã hội.',
    longDescription: 'This course covers all the essential channels of modern digital marketing. You will learn about search engine optimization (SEO), pay-per-click (PPC) advertising, social media marketing, content marketing, and email marketing. Perfect for beginners.',
    longDescription_vi: 'Khóa học này bao gồm tất cả các kênh thiết yếu của marketing kỹ thuật số hiện đại. Bạn sẽ học về tối ưu hóa công cụ tìm kiếm (SEO), quảng cáo trả tiền cho mỗi lần nhấp chuột (PPC), marketing trên mạng xã hội, marketing nội dung và marketing qua email. Hoàn hảo cho người mới bắt đầu.',
    duration: '4 Weeks',
    level: 'Beginner',
    topics: ['SEO', 'Social Media', 'PPC', 'Content Marketing'],
    category: 'Marketing',
  },
  {
    id: 'seo201',
    title: 'Advanced SEO Strategies',
    provider: 'Search Masters Inc.',
    description: 'Dive deep into technical SEO, link building, and advanced analytics.',
    longDescription: 'Go beyond the basics with advanced SEO techniques. This course explores technical site audits, schema markup, international SEO, advanced link-building tactics, and how to use analytics to drive strategy. Requires some prior SEO knowledge.',
    duration: '6 Weeks',
    level: 'Intermediate',
    topics: ['Technical SEO', 'Analytics', 'Link Building', 'Keyword Research'],
    category: 'Marketing',
  },
  {
    id: 'soc301',
    title: 'Social Media Mastery',
    provider: 'ConnectSphere',
    description: 'Master paid and organic strategies for major social platforms.',
    longDescription: 'Learn to build and execute a successful social media strategy. This course covers content creation, community management, paid advertising campaigns on platforms like Facebook, Instagram, and LinkedIn, and influencer marketing.',
    duration: '5 Weeks',
    level: 'Intermediate',
    topics: ['Social Media Advertising', 'Community Management', 'Content Strategy'],
    category: 'Marketing',
  },
  {
    id: 'anl250',
    title: 'Data Analytics for Marketers',
    provider: 'DataDriven Co.',
    description: 'Learn to track, analyze, and visualize marketing data to make better decisions.',
    longDescription: 'This course teaches you how to leverage data for marketing success. You will learn to use tools like Google Analytics and Google Tag Manager, understand key metrics, perform A/B testing, and create insightful dashboards to report on performance.',
    duration: '8 Weeks',
    level: 'Intermediate',
    topics: ['Google Analytics', 'Data Visualization', 'A/B Testing', 'Reporting'],
    category: 'Marketing',
  },
  {
    id: 'con400',
    title: 'Advanced Content Marketing',
    provider: 'StoryBrand',
    description: 'Develop a content strategy that drives traffic, engagement, and leads.',
    longDescription: 'This advanced course focuses on creating a content ecosystem. You will learn about topic clusters, pillar pages, content promotion, video marketing, podcasting, and how to measure the ROI of your content efforts.',
    duration: '6 Weeks',
    level: 'Advanced',
    topics: ['Content Strategy', 'Video Marketing', 'Lead Generation', 'Content ROI'],
    category: 'Marketing',
  },
    {
    id: 'py101',
    title: 'Python for Absolute Beginners',
    title_vi: 'Python cho người mới bắt đầu',
    provider: 'CodeCrafters Academy',
    description: 'Learn the fundamentals of Python programming, one of the most popular languages for web, data, and AI.',
    description_vi: 'Học các nguyên tắc cơ bản của lập trình Python, một trong những ngôn ngữ phổ biến nhất cho web, dữ liệu và AI.',
    longDescription: 'This course starts from scratch, teaching you variables, data types, loops, functions, and basic data structures. You will build several small projects to solidify your understanding. No prior programming experience is required.',
    longDescription_vi: 'Khóa học này bắt đầu từ đầu, dạy bạn về biến, kiểu dữ liệu, vòng lặp, hàm và các cấu trúc dữ liệu cơ bản. Bạn sẽ xây dựng một số dự án nhỏ để củng cố kiến thức của mình. Không yêu cầu kinh nghiệm lập trình trước đó.',
    duration: '6 Weeks',
    level: 'Beginner',
    topics: ['Python', 'Programming Fundamentals', 'Algorithms'],
    category: 'Programming',
  },
  {
    id: 'js101',
    title: 'JavaScript Essentials',
    title_vi: 'JavaScript thiết yếu',
    provider: 'Web Wizards',
    description: 'Master the core concepts of JavaScript to build interactive and dynamic websites.',
    description_vi: 'Nắm vững các khái niệm cốt lõi của JavaScript để xây dựng các trang web tương tác và năng động.',
    longDescription: 'Explore the language of the web. This course covers the DOM, events, modern ES6+ syntax, and asynchronous programming. It is the first step towards becoming a front-end or full-stack developer.',
    longDescription_vi: 'Khám phá ngôn ngữ của web. Khóa học này bao gồm DOM, sự kiện, cú pháp ES6+ hiện đại và lập trình bất đồng bộ. Đây là bước đầu tiên để trở thành một nhà phát triển front-end hoặc full-stack.',
    duration: '5 Weeks',
    level: 'Beginner',
    topics: ['JavaScript', 'Web Development', 'DOM Manipulation', 'ES6'],
    category: 'Programming',
  },
  {
    id: 'sec101',
    title: 'Cybersecurity Fundamentals',
    provider: 'CyberSafe Institute',
    description: 'An introduction to the world of cybersecurity, covering threats, vulnerabilities, and defenses.',
    longDescription: 'Understand the landscape of cybersecurity. Learn about network security, malware, cryptography, and security policies. This course is ideal for anyone looking to start a career in information security.',
    duration: '4 Weeks',
    level: 'Beginner',
    topics: ['Cybersecurity', 'Network Security', 'Cryptography', 'Risk Management'],
    category: 'IT',
  },
  {
    id: 'ux101',
    title: 'UI/UX Design Fundamentals',
    provider: 'Design Minds',
    description: 'Learn the principles of creating user-friendly and visually appealing digital products.',
    longDescription: 'This course covers user research, wireframing, prototyping, and visual design principles. You will learn to use popular design tools like Figma to create intuitive interfaces that provide a great user experience.',
    duration: '6 Weeks',
    level: 'Beginner',
    topics: ['UI Design', 'UX Research', 'Wireframing', 'Prototyping', 'Figma'],
    category: 'Design',
  },
  {
    id: 'db150',
    title: 'SQL for Data Analysis',
    provider: 'DataDriven Co.',
    description: 'Learn to write SQL queries to extract, manipulate, and analyze data from relational databases.',
    longDescription: 'SQL is a fundamental skill for any data professional. This course teaches you how to write complex queries, join tables, and perform aggregations to answer business questions using data. Works with PostgreSQL, MySQL, and SQL Server.',
    duration: '4 Weeks',
    level: 'Beginner',
    topics: ['SQL', 'Data Analysis', 'Database', 'PostgreSQL'],
    category: 'Data Science',
  },
  {
    id: 'cld201',
    title: 'Introduction to Cloud Computing with AWS',
    provider: 'CloudGurus',
    description: 'Understand the core concepts of cloud computing and the foundational services of AWS.',
    longDescription: 'This course demystifies the cloud. You will learn about key AWS services like EC2, S3, RDS, and VPC. It provides the knowledge needed to prepare for the AWS Certified Cloud Practitioner exam.',
    duration: '5 Weeks',
    level: 'Intermediate',
    topics: ['Cloud Computing', 'AWS', 'IaaS', 'PaaS', 'SaaS'],
    category: 'IT',
  },
  {
    id: 'ds201',
    title: 'Data Science Kickstart',
    provider: 'DataDriven Co.',
    description: 'An introduction to the data science workflow, from data cleaning to modeling and visualization.',
    longDescription: 'Using Python libraries like Pandas, NumPy, and Matplotlib, you will learn how to process messy data, explore datasets for insights, and build simple predictive models. Some Python knowledge is recommended.',
    duration: '8 Weeks',
    level: 'Intermediate',
    topics: ['Data Science', 'Python', 'Pandas', 'Data Visualization', 'Machine Learning'],
    category: 'Data Science',
  },
  {
    id: 'web310',
    title: 'Modern Web Development with React',
    provider: 'Web Wizards',
    description: 'Build fast, modern, single-page applications using the React library.',
    longDescription: 'Dive deep into the React ecosystem. Learn about components, state, props, hooks, and routing. You will build a complete web application from scratch. Strong JavaScript knowledge is required.',
    duration: '8 Weeks',
    level: 'Advanced',
    topics: ['React', 'JavaScript', 'Frontend Development', 'State Management'],
    category: 'Programming',
  },
  {
    id: 'web320',
    title: 'Backend Development with Node.js',
    provider: 'Web Wizards',
    description: 'Build scalable, high-performance backend services and APIs using Node.js and Express.',
    longDescription: 'Learn to build the server-side of web applications. This course covers Node.js, the Express framework, REST API design, and database integration with MongoDB. Requires solid JavaScript knowledge.',
    duration: '7 Weeks',
    level: 'Advanced',
    topics: ['Node.js', 'Backend Development', 'API', 'Express', 'MongoDB'],
    category: 'Programming',
  },
  {
    id: 'ml350',
    title: 'Machine Learning in Practice',
    provider: 'AI Innovators',
    description: 'Implement and evaluate common machine learning algorithms for regression, classification, and clustering.',
    longDescription: 'Go beyond the theory and apply machine learning to real-world problems. This course covers Scikit-learn, feature engineering, model selection, and techniques like decision trees, SVMs, and neural networks.',
    duration: '10 Weeks',
    level: 'Advanced',
    topics: ['Machine Learning', 'Python', 'Scikit-learn', 'Predictive Modeling'],
    category: 'Data Science',
  },
  {
    id: 'sec401',
    title: 'Ethical Hacking and Penetration Testing',
    provider: 'CyberSafe Institute',
    description: 'Learn the tools and techniques used by ethical hackers to find and exploit vulnerabilities.',
    longDescription: 'This hands-on course teaches you how to think like an attacker to better defend your systems. You will learn about reconnaissance, scanning, exploitation, and post-exploitation frameworks. A strong networking and OS background is required.',
    duration: '8 Weeks',
    level: 'Advanced',
    topics: ['Ethical Hacking', 'Penetration Testing', 'Cybersecurity', 'Kali Linux'],
    category: 'IT',
  },
  {
    id: 'mob310',
    title: 'iOS App Development with Swift',
    provider: 'Mobile Masters',
    description: 'Learn to build beautiful, native mobile apps for iPhone and iPad using Swift and SwiftUI.',
    longDescription: 'From the basics of the Swift language to advanced SwiftUI layouts and data flow, this course guides you through building a complete iOS application and preparing it for the App Store.',
    duration: '9 Weeks',
    level: 'Intermediate',
    topics: ['iOS Development', 'Swift', 'SwiftUI', 'Mobile Apps', 'Xcode'],
    category: 'Programming',
  },
  {
    id: 'mob320',
    title: 'Android App Development with Kotlin',
    provider: 'Mobile Masters',
    description: 'Develop modern, robust Android applications using the Kotlin programming language.',
    longDescription: 'This course covers the fundamentals of Android development, including Activities, Layouts with XML, Jetpack Compose, and connecting to APIs. You will build a portfolio-ready app.',
    duration: '9 Weeks',
    level: 'Intermediate',
    topics: ['Android Development', 'Kotlin', 'Jetpack Compose', 'Mobile Apps'],
    category: 'Programming',
  },
  {
    id: 'dev300',
    title: 'Introduction to DevOps',
    provider: 'SysAdmins United',
    description: 'Learn the culture, tools, and practices of DevOps to improve software development and deployment.',
    longDescription: 'This course introduces the DevOps lifecycle, including continuous integration (CI), continuous delivery (CD), infrastructure as code (IaC) with Terraform, and containerization with Docker.',
    duration: '6 Weeks',
    level: 'Intermediate',
    topics: ['DevOps', 'CI/CD', 'Docker', 'Terraform', 'Agile'],
    category: 'IT',
  },
  {
    id: 'vcs101',
    title: 'Mastering Git and GitHub',
    provider: 'CodeCrafters Academy',
    description: 'Learn version control with Git, an essential tool for every developer.',
    longDescription: 'Understand how to track changes in your code, collaborate with others, and manage projects on GitHub. This course covers everything from basic commits to complex branching and merging strategies.',
    duration: '2 Weeks',
    level: 'Beginner',
    topics: ['Git', 'GitHub', 'Version Control', 'Software Development'],
    category: 'Programming',
  },
  {
    id: 'py301',
    title: 'Advanced Python Programming',
    provider: 'CodeCrafters Academy',
    description: 'Go beyond the basics with advanced Python features and best practices.',
    longDescription: 'This course is for those already comfortable with Python basics. Topics include decorators, generators, context managers, concurrency, and performance optimization. Essential for writing clean, efficient, and professional Python code.',
    duration: '6 Weeks',
    level: 'Advanced',
    topics: ['Python', 'Advanced Programming', 'Concurrency', 'Performance'],
    category: 'Programming',
  },
  {
    id: 'cld202',
    title: 'Microsoft Azure Fundamentals',
    provider: 'CloudGurus',
    description: 'Grasp the fundamentals of Microsoft Azure and its core cloud services.',
    longDescription: 'A parallel to our AWS course, this introduces you to the Azure platform. Learn about Azure virtual machines, storage, databases, and identity services. Prepares you for the AZ-900 exam.',
    duration: '5 Weeks',
    level: 'Intermediate',
    topics: ['Cloud Computing', 'Azure', 'Microsoft', 'IaaS', 'PaaS'],
    category: 'IT',
  },

// --- Language Courses ---
  {
    id: 'es101',
    title: 'Spanish for Beginners',
    provider: 'LinguaLink',
    description: 'Start your journey to fluency in Spanish. Learn essential grammar, vocabulary, and conversational phrases.',
    longDescription: 'This course is designed for absolute beginners. You will learn greetings, basic sentence structures, present tense verb conjugations, and vocabulary for everyday situations like travel and dining.',
    duration: '8 Weeks',
    level: 'Beginner',
    topics: ['Spanish', 'Grammar', 'Vocabulary', 'Conversation'],
    category: 'Languages',
  },
  {
    id: 'fr101',
    title: 'French for Beginners',
    provider: 'GlobalTongue Institute',
    description: 'An introduction to the French language, focusing on pronunciation, basic grammar, and culture.',
    longDescription: 'Bonjour! Learn the fundamentals of French, from the alphabet and numbers to common phrases and verb conjugations. The course includes cultural notes to enhance your learning experience.',
    duration: '8 Weeks',
    level: 'Beginner',
    topics: ['French', 'Pronunciation', 'Culture', 'Grammar'],
    category: 'Languages',
  },
  {
    id: 'jp101',
    title: 'Japanese for Beginners (JLPT N5)',
    provider: 'Sakura Language School',
    description: 'Learn to read Hiragana and Katakana, and master basic Japanese grammar and vocabulary.',
    longDescription: 'This course is the first step towards mastering Japanese. It covers the core building blocks of the language and prepares students for the Japanese Language Proficiency Test (JLPT) N5 level.',
    duration: '10 Weeks',
    level: 'Beginner',
    topics: ['Japanese', 'Hiragana', 'Katakana', 'JLPT N5'],
    category: 'Languages',
  },
  {
    id: 'cn101',
    title: 'Mandarin Chinese - HSK 1',
    provider: 'Dragon Language Center',
    description: 'Learn the basics of Mandarin, including Pinyin, tones, and the 150 words required for HSK Level 1.',
    longDescription: 'Start speaking the world\'s most spoken language. This course focuses on practical, simple conversations, basic character recognition, and mastering the challenging tonal system of Mandarin Chinese.',
    duration: '10 Weeks',
    level: 'Beginner',
    topics: ['Mandarin', 'Chinese', 'Pinyin', 'HSK', 'Tones'],
    category: 'Languages',
  },
  {
    id: 'de101',
    title: 'German for Travel',
    provider: 'SpeakEasy Learning',
    description: 'Learn essential German phrases and cultural tips for your next trip to Germany, Austria, or Switzerland.',
    longDescription: 'This practical course focuses on conversational skills needed for travel, such as ordering food, asking for directions, booking a hotel, and making small talk. Grammar is kept to a minimum.',
    duration: '4 Weeks',
    level: 'Beginner',
    topics: ['German', 'Travel', 'Conversation', 'Culture'],
    category: 'Languages',
  },
  {
    id: 'it101',
    title: 'Italian Language and Culture',
    provider: 'LinguaLink',
    description: 'An introduction to the beautiful Italian language and the rich culture of Italy.',
    longDescription: 'Learn to speak basic Italian while exploring Italy\'s food, art, and history. This course blends language lessons with cultural insights to provide a holistic learning experience.',
    duration: '7 Weeks',
    level: 'Beginner',
    topics: ['Italian', 'Culture', 'Grammar', 'Conversation'],
    category: 'Languages',
  },
  {
    id: 'kr101',
    title: 'Korean for Beginners',
    provider: 'Seoul Language Hub',
    description: 'Learn to read and write Hangeul, the Korean alphabet, and start speaking basic Korean.',
    longDescription: 'Dive into the world of K-Pop and K-Dramas by learning the language. This course covers the Hangeul alphabet, basic sentence structure, and common vocabulary for everyday interactions.',
    duration: '8 Weeks',
    level: 'Beginner',
    topics: ['Korean', 'Hangeul', 'Grammar', 'K-Culture'],
    category: 'Languages',
  },
  {
    id: 'es201',
    title: 'Conversational Spanish',
    provider: 'LinguaLink',
    description: 'Improve your speaking and listening skills to hold confident conversations in Spanish.',
    longDescription: 'This course is for those who know some basic Spanish grammar but want to improve their fluency. It focuses on conversation practice, idiomatic expressions, and listening comprehension. Past tenses are introduced and practiced.',
    duration: '6 Weeks',
    level: 'Intermediate',
    topics: ['Spanish', 'Conversation', 'Fluency', 'Listening'],
    category: 'Languages',
  },
  {
    id: 'fr201',
    title: 'Intermediate French',
    provider: 'GlobalTongue Institute',
    description: 'Build upon your French foundation by mastering past tenses and more complex sentence structures.',
    longDescription: 'This course dives into the Passé Composé and Imparfait, the subjunctive mood, and more advanced vocabulary. It is designed to take your French from a beginner to a confident intermediate level.',
    duration: '8 Weeks',
    level: 'Intermediate',
    topics: ['French', 'Grammar', 'Passé Composé', 'Vocabulary'],
    category: 'Languages',
  },
  {
    id: 'jp201',
    title: 'Intermediate Japanese (JLPT N4)',
    provider: 'Sakura Language School',
    description: 'Expand your grammar, vocabulary, and Kanji knowledge to prepare for the JLPT N4 exam.',
    longDescription: 'This course builds on a beginner foundation, introducing around 150 new Kanji and more complex grammatical patterns. Focuses on reading and understanding short stories and articles.',
    duration: '12 Weeks',
    level: 'Intermediate',
    topics: ['Japanese', 'Kanji', 'Grammar', 'JLPT N4', 'Reading'],
    category: 'Languages',
  },
  {
    id: 'en301',
    title: 'Business English Communication',
    provider: 'Executive Language Pro',
    description: 'Master the English needed for professional environments, including meetings, presentations, and emails.',
    longDescription: 'Designed for non-native speakers with a high level of English, this course refines communication skills for the workplace. It covers negotiation language, presentation skills, and professional writing etiquette.',
    duration: '6 Weeks',
    level: 'Advanced',
    topics: ['Business English', 'Public Speaking', 'Negotiation', 'Professional Writing'],
    category: 'Languages',
  },
  {
    id: 'ar101',
    title: 'Arabic for Beginners',
    provider: 'Oasis Language Institute',
    description: 'Learn to read and write the Arabic script and master the basics of Modern Standard Arabic.',
    longDescription: 'This course introduces the Arabic alphabet and basic grammar. Students will learn to introduce themselves, ask simple questions, and understand the fundamentals of the language used across the Arab world.',
    duration: '10 Weeks',
    level: 'Beginner',
    topics: ['Arabic', 'Modern Standard Arabic', 'Script', 'Grammar'],
    category: 'Languages',
  },
  {
    id: 'ru101',
    title: 'Russian for Beginners',
    provider: 'Red Star Languages',
    description: 'Learn the Cyrillic alphabet and the fundamentals of Russian grammar and pronunciation.',
    longDescription: 'This course demystifies the Russian language, starting with the alphabet and moving onto the case system and basic verb conjugations. You will learn essential phrases for introductions and travel.',
    duration: '9 Weeks',
    level: 'Beginner',
    topics: ['Russian', 'Cyrillic', 'Grammar', 'Case System'],
    category: 'Languages',
  },
  {
    id: 'pt101',
    title: 'Brazilian Portuguese for Beginners',
    provider: 'LinguaLink',
    description: 'Learn the vibrant language of Brazil, focusing on its unique pronunciation and expressions.',
    longDescription: 'This course teaches the basics of Brazilian Portuguese for conversation. You will learn grammar and vocabulary through the lens of Brazilian culture, music, and daily life.',
    duration: '8 Weeks',
    level: 'Beginner',
    topics: ['Portuguese', 'Brazil', 'Conversation', 'Grammar'],
    category: 'Languages',
  },
  {
    id: 'cn102',
    title: 'Mandarin Chinese - HSK 2',
    provider: 'Dragon Language Center',
    description: 'Build on your HSK 1 knowledge to discuss more topics and expand your vocabulary to 300 words.',
    longDescription: 'This course prepares students for the HSK Level 2 test. You will learn to discuss topics like weather, travel, and work in simple terms, and improve your character recognition and sentence patterns.',
    duration: '10 Weeks',
    level: 'Beginner',
    topics: ['Mandarin', 'Chinese', 'HSK', 'Vocabulary', 'Grammar'],
    category: 'Languages',
  },
  {
    id: 'es301',
    title: 'Advanced Spanish Grammar',
    provider: 'LinguaLink',
    description: 'Master the most complex aspects of Spanish grammar, including the subjunctive and conditional tenses.',
    longDescription: 'For the serious Spanish student, this course dives deep into the nuances of grammar that separate intermediate speakers from advanced ones. Heavy focus on the subjunctive mood, if-clauses, and idiomatic structures.',
    duration: '8 Weeks',
    level: 'Advanced',
    topics: ['Spanish', 'Advanced Grammar', 'Subjunctive', 'Fluency'],
    category: 'Languages',
  },
  {
    id: 'cn301',
    title: 'Advanced Mandarin Chinese (HSK 4)',
    provider: 'Dragon Language Center',
    description: 'Reach a new level of fluency, preparing for the HSK 4 exam with 1200 vocabulary words.',
    longDescription: 'This course enables you to converse in Chinese on a wide range of topics and to communicate with native speakers. You will practice reading, writing, and speaking on complex subjects. Requires HSK 3 or equivalent.',
    duration: '14 Weeks',
    level: 'Advanced',
    topics: ['Mandarin', 'Chinese', 'HSK', 'Fluency', 'Reading'],
    category: 'Languages',
  },
  
// --- Economy Courses ---
  {
    id: 'eco101',
    title: 'Principles of Microeconomics',
    provider: 'EconVision Institute',
    description: 'Understand how individuals and firms make decisions and how they interact in markets.',
    longDescription: 'This foundational course covers the core concepts of economics, including supply and demand, elasticity, market structures, and market failure. Essential for understanding the economy around you.',
    duration: '6 Weeks',
    level: 'Beginner',
    topics: ['Microeconomics', 'Supply and Demand', 'Market Structure', 'Elasticity'],
    category: 'Economics',
  },
  {
    id: 'eco102',
    title: 'Principles of Macroeconomics',
    provider: 'EconVision Institute',
    description: 'Study the economy as a whole, including inflation, unemployment, and economic growth.',
    longDescription: 'Explore the forces that shape entire economies. This course covers GDP, monetary and fiscal policy, international trade, and the business cycle. Learn how governments and central banks manage the economy.',
    duration: '6 Weeks',
    level: 'Beginner',
    topics: ['Macroeconomics', 'GDP', 'Fiscal Policy', 'Monetary Policy', 'Inflation'],
    category: 'Economics',
  },
  {
    id: 'fin210',
    title: 'Introduction to Financial Markets',
    provider: 'Global Finance School',
    description: 'Learn about the role and function of financial markets, including stocks, bonds, and derivatives.',
    longDescription: 'This course provides a comprehensive overview of the financial system. You will learn about different types of financial instruments, how they are traded, and the institutions that participate in these markets.',
    duration: '7 Weeks',
    level: 'Intermediate',
    topics: ['Finance', 'Stock Market', 'Bonds', 'Derivatives', 'Investment'],
    category: 'Economics',
  },
  {
    id: 'eco310',
    title: 'International Trade and Policy',
    provider: 'MarketMind Academy',
    description: 'Analyze the theories of international trade, trade barriers, and global trade agreements.',
    longDescription: 'Why do nations trade? This course examines the models of comparative advantage, the effects of tariffs and quotas, and the role of organizations like the WTO. Requires knowledge of basic microeconomics.',
    duration: '6 Weeks',
    level: 'Advanced',
    topics: ['International Trade', 'Economics', 'Globalization', 'Trade Policy'],
    category: 'Economics',
  },
  {
    id: 'eco320',
    title: 'Behavioral Economics',
    provider: 'EconVision Institute',
    description: 'Explore how psychological factors influence economic decision-making.',
    longDescription: 'This course challenges traditional economic assumptions by incorporating insights from psychology. Learn about biases, heuristics, prospect theory, and how these concepts can be used to "nudge" behavior.',
    duration: '5 Weeks',
    level: 'Advanced',
    topics: ['Behavioral Economics', 'Psychology', 'Decision Making', 'Nudge Theory'],
    category: 'Economics',
  },
  {
    id: 'eco350',
    title: 'Introduction to Econometrics',
    provider: 'DataDriven Co.',
    description: 'Apply statistical methods to economic data to test theories and forecast future trends.',
    longDescription: 'Learn the fundamentals of regression analysis, the workhorse of econometrics. This course teaches you how to build and interpret economic models using real-world data. A background in statistics is recommended.',
    duration: '8 Weeks',
    level: 'Advanced',
    topics: ['Econometrics', 'Statistics', 'Regression Analysis', 'Forecasting'],
    category: 'Economics',
  },
  {
    id: 'eco330',
    title: 'Economics of Developing Countries',
    provider: 'Global Vision Foundation',
    description: 'Study the economic challenges and policies in low and middle-income countries.',
    longDescription: 'This course explores topics crucial to development, including poverty, inequality, health, education, and the role of foreign aid. It examines theories of economic growth and development strategies.',
    duration: '7 Weeks',
    level: 'Advanced',
    topics: ['Development Economics', 'Poverty', 'Inequality', 'Global Health'],
    category: 'Economics',
  },
  {
    id: 'fin360',
    title: 'Cryptocurrency and Blockchain Economics',
    provider: 'Future Finance Academy',
    description: 'Understand the technology and economic principles behind Bitcoin, Ethereum, and other digital assets.',
    longDescription: 'This course covers the fundamentals of blockchain technology, the economics of cryptocurrencies, consensus mechanisms, and the basics of Decentralized Finance (DeFi).',
    duration: '6 Weeks',
    level: 'Advanced',
    topics: ['Cryptocurrency', 'Blockchain', 'Bitcoin', 'DeFi', 'Economics'],
    category: 'Economics',
  },
  {
    id: 'eco201',
    title: 'Intermediate Microeconomics',
    provider: 'EconVision Institute',
    description: 'A more rigorous, calculus-based approach to the behavior of consumers and firms.',
    longDescription: 'This course builds on the principles-level class with a more formal, mathematical treatment of consumer theory, producer theory, and market equilibrium. Essential for those pursuing a degree in economics.',
    duration: '8 Weeks',
    level: 'Intermediate',
    topics: ['Microeconomics', 'Consumer Theory', 'Calculus', 'Game Theory'],
    category: 'Economics',
  },
  {
    id: 'eco202',
    title: 'Intermediate Macroeconomics',
    provider: 'EconVision Institute',
    description: 'Explore modern macroeconomic models of growth, business cycles, and policy.',
    longDescription: 'Dive deeper into the models that economists use to understand the big picture, including the IS-LM model, the Solow growth model, and theories of unemployment and inflation. Requires principles of macroeconomics.',
    duration: '8 Weeks',
    level: 'Intermediate',
    topics: ['Macroeconomics', 'Economic Models', 'IS-LM', 'Solow Model'],
    category: 'Economics',
  },
  {
    id: 'eco340',
    title: 'Public Finance and Taxation',
    provider: 'MarketMind Academy',
    description: 'Analyze government spending and taxation and their effects on the economy.',
    longDescription: 'This course covers the rationale for government intervention, analysis of public goods and externalities, and the economic effects of different types of taxes, such as income, sales, and corporate taxes.',
    duration: '6 Weeks',
    level: 'Advanced',
    topics: ['Public Finance', 'Taxation', 'Government Spending', 'Public Policy'],
    category: 'Economics',
  },
  {
    id: 'eco410',
    title: 'Game Theory for Strategists',
    provider: 'Strategic Minds Inc.',
    description: 'Learn to analyze strategic interactions between rational decision-makers.',
    longDescription: 'Game theory is the study of strategy. This course covers simultaneous and sequential games, Nash equilibrium, and applications in business, politics, and everyday life. A strong analytical mindset is required.',
    duration: '6 Weeks',
    level: 'Advanced',
    topics: ['Game Theory', 'Strategy', 'Nash Equilibrium', 'Decision Making'],
    category: 'Economics',
  },
  {
    id: 'fin370',
    title: 'Real Estate Economics and Finance',
    provider: 'Global Finance School',
    description: 'Analyze real estate markets and learn the principles of property valuation and investment.',
    longDescription: 'This course covers the determinants of real estate values, the development process, and the financing of residential and commercial properties, including mortgage finance and investment analysis.',
    duration: '7 Weeks',
    level: 'Advanced',
    topics: ['Real Estate', 'Finance', 'Investment', 'Valuation', 'Mortgage'],
    category: 'Economics',
  },
  {
    id: 'eco380',
    title: 'Health Economics',
    provider: 'Wellbeing Institute',
    description: 'Apply economic principles to understand the structure and performance of the healthcare industry.',
    longDescription: 'This course examines the unique aspects of health and healthcare markets, including the demand for health, the role of insurance, and the behavior of physicians and hospitals. Discusses various healthcare systems around the world.',
    duration: '6 Weeks',
    level: 'Advanced',
    topics: ['Health Economics', 'Healthcare Policy', 'Insurance', 'Public Health'],
    category: 'Economics',
  },
  {
    id: 'eco280',
    title: 'Environmental Economics',
    provider: 'Green World Academy',
    description: 'Use economic tools to analyze environmental problems and evaluate policy solutions.',
    longDescription: 'This course explores topics like pollution, climate change, and natural resource management from an economic perspective. It covers concepts like externalities, public goods, and the valuation of environmental quality.',
    duration: '6 Weeks',
    level: 'Intermediate',
    topics: ['Environmental Economics', 'Climate Change', 'Sustainability', 'Policy'],
    category: 'Economics',
  },
  {
    id: 'eco290',
    title: 'The Global Economy',
    provider: 'MarketMind Academy',
    description: 'An accessible overview of the key institutions and forces shaping the world economy.',
    longDescription: 'This course is for those without a deep economics background who want to understand globalization, international finance (exchange rates, capital flows), and major global economic events. Less technical than International Trade.',
    duration: '5 Weeks',
    level: 'Intermediate',
    topics: ['Globalization', 'International Finance', 'World Economy', 'Development'],
    category: 'Economics',
  }
];

/**
 * A custom hook to access the list of available courses.
 * @returns An array of `Course` objects.
 */
export const useCourses = (): Course[] => {
  return courses;
};
